/*
#====================================================================================
#
# SCRIPT:  cambio_dirección_entrega_validada
# AUTOR:   JORDI BONILLO
# FECHA:   12-02-2024
#
# SQL Script - Microsoft SQL SERVER
# 
#==================================================================================== 
#
# Modifica dirección de entrega de albarán, preparación y pedido cuando la
# entrega ya se ha generado y validado.
#
#==================================================================================== 
*/


DECLARE @codnuevadir VARCHAR(10)
DECLARE @numpedido VARCHAR(20)
DECLARE @preparacion VARCHAR(20)
DECLARE @albaran VARCHAR(20)
DECLARE @factura VARCHAR(20)

-- ########## A MODIFICAR ###########
SET @codnuevadir='xxxx'
SET @numpedido='xxxxxxxxx'
SET @preparacion='xxxxxxxx'
SET @albaran='xxxxxxxx'
SET @factura='xxxxxxxx'
-- ##################################


-- CAMBIA DIRECCIÓN ENTREGA EN SORDER
UPDATE 
	SMIRA.SORDER 
SET 
	SORDER.BPAADD_0 = BPA.BPAADD_0,
	SORDER.BPDNAM_0 = BPA.BPADES_0,
	SORDER.BPDADDLIG_0= BPA.BPAADDLIG_0,
	SORDER.BPDADDLIG_1= BPA.BPAADDLIG_2,
	SORDER.BPDADDLIG_2= BPA.BPAADDLIG_2,
	SORDER.BPDPOSCOD_0 = BPA.POSCOD_0,
	SORDER.BPDCTY_0 = BPA.CTY_0,
	SORDER.BPDSAT_0 = BPA.SAT_0,
	SORDER.BPDCRY_0 = BPA.CRY_0,
	SORDER.BPDCRYNAM_0 = BPA.CRYNAM_0
FROM 
	SMIRA.SORDER AS SOH
INNER JOIN 
	SMIRA.BPADDRESS AS BPA ON BPA.BPANUM_0=SOH.BPCORD_0 AND BPA.BPAADD_0=@codnuevadir
WHERE 
	SOH.SOHNUM_0=@numpedido
  
UPDATE SMIRA.SORDERP SET BPAADD_0=@codnuevadir WHERE SOHNUM_0=@numpedido
  
UPDATE SMIRA.SORDERQ SET BPAADD_0=@codnuevadir WHERE SOHNUM_0=@numpedido



-- CAMBIA DIRECCIÓN A PREPARACIÓN
UPDATE 
	SMIRA.STOPREH 
SET 
	BPAADD_0=@codnuevadir 
WHERE 
	PRHNUM_0=@preparacion


  
-- CAMBIA DIRECCIÓN A ENTREGA
UPDATE 
	SMIRA.SDELIVERY
SET 
	SDELIVERY.BPAADD_0 = BPA.BPAADD_0,
	SDELIVERY.BPDNAM_0 = BPA.BPADES_0,
	SDELIVERY.BPDADDLIG_0= BPA.BPAADDLIG_0,
	SDELIVERY.BPDADDLIG_1= BPA.BPAADDLIG_2,
	SDELIVERY.BPDADDLIG_2= BPA.BPAADDLIG_2,
	SDELIVERY.BPDPOSCOD_0 = BPA.POSCOD_0,
	SDELIVERY.BPDCTY_0 = BPA.CTY_0,
	SDELIVERY.BPDSAT_0 = BPA.SAT_0,
	SDELIVERY.BPDCRY_0 = BPA.CRY_0,
	SDELIVERY.BPDCRYNAM_0 = BPA.CRYNAM_0
FROM 
	SMIRA.SDELIVERY AS SDH
INNER JOIN 
	SMIRA.BPADDRESS AS BPA ON BPA.BPANUM_0=SDH.BPCORD_0 AND BPA.BPAADD_0=@codnuevadir
WHERE 
	SDH.SDHNUM_0=@albaran
  
UPDATE SMIRA.SDELIVERYD SET BPAADD_0=@codnuevadir WHERE SDHNUM_0=@albaran


  
-- CAMBIA DIRECCIÓN A FACTURA
UPDATE 
	SMIRA.SINVOICEV
SET 
	SINVOICEV.BPAADD_0 = BPA.BPAADD_0,
	SINVOICEV.BPDNAM_0 = BPA.BPADES_0,
	SINVOICEV.BPDADDLIG_0= BPA.BPAADDLIG_0,
	SINVOICEV.BPDADDLIG_1= BPA.BPAADDLIG_2,
	SINVOICEV.BPDADDLIG_2= BPA.BPAADDLIG_2,
	SINVOICEV.BPDPOSCOD_0 = BPA.POSCOD_0,
	SINVOICEV.BPDCTY_0 = BPA.CTY_0,
	SINVOICEV.BPDSAT_0 = BPA.SAT_0,
	SINVOICEV.BPDCRY_0 = BPA.CRY_0,
	SINVOICEV.BPDCRYNAM_0 = BPA.CRYNAM_0
FROM 
	SMIRA.SINVOICEV AS SIV
INNER JOIN 
	SMIRA.BPADDRESS AS BPA ON BPA.BPANUM_0=SIV.BPCINV_0 AND BPA.BPAADD_0=@codnuevadir
WHERE 
	SIV.NUM_0=@factura
